import { v } from 'convex/values';
import { internal } from './_generated/api';
import { DatabaseReader, MutationCtx, mutation } from './_generated/server';
import { Descriptions, characters } from '../data/characters';
import * as map from '../data/gentle';
import worldFileJson from '../data/world.json';
import {
  MapContext,
  WorldFile,
  createEntityArgs,
  subtractEntityAnchors,
  validateWorldFile,
} from '../engine/aiTown/worldFile';
import { insertInput } from './aiTown/insertInput';
import { Id } from './_generated/dataModel';
import { createEngine } from './aiTown/main';
import { ENGINE_ACTION_DURATION } from '../engine/constants';
import { detectMismatchedLLMProvider } from './util/llm';
import { Rng } from '../engine/util/rng';
import { COMMON_KNOWLEDGE_ID } from '../engine/prose/contract';
import { appendEntityState } from './prose/store';

// `data/gentle.js` predates docs/07-map-entity-split.md and exports neither `collision` nor
// `anchors`; a map regenerated by `data/convertMap.js` exports both. `WorldMap` derives
// collision from the object layers when it's missing, so an unmigrated map still loads.
const mapModule = map as typeof map & {
  collision?: boolean[][];
  anchors?: Record<string, { x: number; y: number; w: number; h: number; description: string }>;
};

// Anchors are stored as an array sorted by id: iteration order is observable, and docs/05 §10
// requires it to be deterministic.
function serializeAnchors() {
  return Object.entries(mapModule.anchors ?? {})
    .map(([id, anchor]) => ({ id, ...anchor }))
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

const worldFile = worldFileJson as WorldFile;

function mapContext(): MapContext {
  const anchors = new Map(Object.entries(mapModule.anchors ?? {}));
  // The static collision the map ships with, before any load-time subtraction. Derived from the
  // object layers when the map predates docs/07, which is exactly what `WorldMap` does.
  const collision =
    mapModule.collision ??
    Array.from({ length: map.mapwidth }, (_, x) =>
      Array.from({ length: map.mapheight }, (_, y) =>
        map.objmap.some((layer) => (layer[x]?.[y] ?? -1) !== -1),
      ),
    );
  return {
    anchors,
    characters: new Set(characters.map((c) => c.name)),
    width: map.mapwidth,
    height: map.mapheight,
    blocked: (x, y) => collision[x]?.[y] ?? false,
  };
}

/**
 * The map as it should be stored: static collision with every fixed entity's anchor subtracted,
 * so an entity's own physics is the only authority over the tiles it occupies (docs/07 §5.2).
 */
function loadedMap() {
  const context = mapContext();
  const collision =
    mapModule.collision ??
    Array.from({ length: map.mapwidth }, (_, x) =>
      Array.from({ length: map.mapheight }, (_, y) => context.blocked(x, y)),
    );
  const subtracted = subtractEntityAnchors(collision, worldFile, context);
  for (const warning of subtracted.warnings) {
    console.warn(`World file: ${warning}`);
  }
  return subtracted.collision;
}

const init = mutation({
  args: {
    numAgents: v.optional(v.number()),
    // Forces the pre-world-file path, which stays working as the experimental control
    // (docs/07 §6.3).
    useDescriptions: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    detectMismatchedLLMProvider();
    const { worldStatus, engine } = await getOrCreateDefaultWorld(ctx);
    if (worldStatus.status !== 'running') {
      console.warn(
        `Engine ${engine._id} is not active! Run "npx convex run testing:resume" to restart it.`,
      );
      return;
    }
    const shouldCreate = await shouldCreateAgents(
      ctx.db,
      worldStatus.worldId,
      worldStatus.engineId,
    );
    if (!shouldCreate) {
      return;
    }
    const useWorldFile = !args.useDescriptions && worldFile.entities?.length > 0;
    if (!useWorldFile) {
      const toCreate = args.numAgents !== undefined ? args.numAgents : Descriptions.length;
      for (let i = 0; i < toCreate; i++) {
        await insertInput(ctx, worldStatus.worldId, 'createAgent', {
          descriptionIndex: i % Descriptions.length,
        });
      }
      return;
    }

    const { errors, warnings } = validateWorldFile(worldFile, mapContext());
    for (const warning of warnings) {
      console.warn(`World file: ${warning}`);
    }
    if (errors.length > 0) {
      // docs/07 §8: errors block loading. Booting a different world than the one that was
      // authored is worse than not booting.
      throw new Error(`World file is invalid:\n  ${errors.join('\n  ')}`);
    }

    let mobileCreated = 0;
    for (const entity of worldFile.entities) {
      const isMobileActor = entity.kind === 'actor' && entity.mobile;
      if (isMobileActor && args.numAgents !== undefined && mobileCreated >= args.numAgents) {
        continue;
      }
      if (isMobileActor) {
        mobileCreated += 1;
      }
      await insertInput(ctx, worldStatus.worldId, 'createEntity', createEntityArgs(entity));
    }
    console.log(
      `Loaded "${worldFile.meta?.title ?? worldFile.meta?.id ?? 'world'}": ${worldFile.entities.length} entities`,
    );
  },
});
export default init;

async function getOrCreateDefaultWorld(ctx: MutationCtx) {
  const now = Date.now();

  let worldStatus = await ctx.db
    .query('worldStatus')
    .filter((q) => q.eq(q.field('isDefault'), true))
    .unique();
  if (worldStatus) {
    const engine = (await ctx.db.get(worldStatus.engineId))!;
    return { worldStatus, engine };
  }

  const engineId = await createEngine(ctx);
  const engine = (await ctx.db.get(engineId))!;
  // Recorded on the world so a run is reproducible from it plus the input log (docs/05 §10),
  // and sourced from `meta.seed` in the world file when it declares one (docs/05 §2).
  const seed = worldFile.meta?.seed ?? Date.now() >>> 0;
  console.log(`Creating world with simulation seed ${seed}`);
  // docs/05 §5.3: authored common knowledge is installed at world creation rather than through an
  // input, for the same reason `world_rules` and the map are — it is configuration the world is
  // built from, not something that happened in it. Seeding it through an input would mean a second
  // writer for a document whose whole guarantee is that it has exactly one.
  const commonKnowledge = worldFile.common_knowledge?.trim();
  const worldId = await ctx.db.insert('worlds', {
    nextId: 0,
    agents: [],
    conversations: [],
    players: [],
    seed,
    rng: Rng.fromSeed(seed).serialize(),
    commonKnowledgeVersion: commonKnowledge ? 1 : 0,
  });
  if (commonKnowledge) {
    await appendEntityState(
      ctx.db,
      worldId,
      COMMON_KNOWLEDGE_ID,
      1,
      { state: commonKnowledge },
      now,
    );
  }
  const worldStatusId = await ctx.db.insert('worldStatus', {
    engineId: engineId,
    isDefault: true,
    lastViewed: now,
    status: 'running',
    worldId: worldId,
  });
  worldStatus = (await ctx.db.get(worldStatusId))!;
  await ctx.db.insert('maps', {
    worldId,
    width: map.mapwidth,
    height: map.mapheight,
    tileSetUrl: map.tilesetpath,
    tileSetDimX: map.tilesetpxw,
    tileSetDimY: map.tilesetpxh,
    tileDim: map.tiledim,
    bgTiles: map.bgtiles,
    objectTiles: map.objmap,
    animatedSprites: map.animatedsprites,
    collision: loadedMap(),
    anchors: serializeAnchors(),
  });
  // World-level prose the prompt layer reads. Written once, like the map.
  await ctx.db.insert('worldDescriptions', {
    worldId,
    worldRules: worldFile.world_rules ?? '',
    godPersona: worldFile.god?.persona,
    godHiddenRules: worldFile.god?.hidden_rules,
    maxTranscriptTurns: worldFile.god?.max_transcript_turns,
    godGateEnabled: worldFile.god?.gate?.enabled ?? true,
  });
  await ctx.scheduler.runAfter(0, internal.aiTown.main.runStep, {
    worldId,
    generationNumber: engine.generationNumber,
    maxDuration: ENGINE_ACTION_DURATION,
  });
  return { worldStatus, engine };
}

async function shouldCreateAgents(
  db: DatabaseReader,
  worldId: Id<'worlds'>,
  engineId: Id<'engines'>,
) {
  const world = await db.get(worldId);
  if (!world) {
    throw new Error(`Invalid world ID: ${worldId}`);
  }
  if (world.agents.length > 0) {
    return false;
  }
  const unactionedJoinInputs = await db
    .query('inputs')
    .withIndex('byInputNumber', (q) => q.eq('engineId', engineId))
    .order('asc')
    .filter((q) => q.eq(q.field('name'), 'createAgent'))
    .filter((q) => q.eq(q.field('returnValue'), undefined))
    .first();
  if (unactionedJoinInputs) {
    return false;
  }
  return true;
}
